name: 'Update version'
description: 'Updates the version'
inputs:
  version-type:
    description: 'Which version type to update (patch, minor or major)'
    required: true
runs:
  using: 'node20'
  main: 'update-version.js'
