name: New Language

on:
  issues:
    types: [opened, edited]

jobs:
  add_new_language:
    name: Add new language
    if: ${{ startsWith(github.event.issue.title, 'Add new language') }}
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 9
      - uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: pnpm
      - name: Install dependencies
        run: pnpm install
      - name: Add language
        uses: ./.github/actions/add-language
        with:
          trakt-tools-bot-token: '${{ secrets.TRAKT_TOOLS_BOT_TOKEN }}'
          crowdin-api-key: '${{ secrets.CROWDIN_API_KEY }}'
          crowdin-project-id: '${{ secrets.CROWDIN_PROJECT_ID }}'
